services:
  scdl:
    build:
      context: .
    container_name: soundcloud-downloader
    restart: unless-stopped
    tty: true
    stdin_open: true
    # network_mode: host
    # privileged: true
    volumes:
      - /mnt/Media/music/soundcloud/lukas-wolter-779075141:/Music/SoundCloud/lukas-wolter-779075141
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
